In [1]:
import nltk
import pandas as pd
import numpy as np
import re 
import string
from nltk.corpus import stopwords

In [2]:
text = """Both versions convey a topic; it’s pretty easy to predict that the paragraph will be about epidemiological 
evidence, but only the second version establishes an argumentative point and puts it in context. The paragraph doesn’t 
just describe the epidemiological evidence; it shows how epidemiology is telling the same story as etiology. Similarly, 
while Version A doesn’t relate to anything in particular, Version B immediately suggests that the prior paragraph addresses 
the biological pathway (i.e. etiology) of a disease and that the new paragraph will bolster the emerging hypothesis with a
different kind of evidence. As a reader, it’s easy to keep track of how the paragraph about cells and chemicals and such 
relates to the paragraph about populations in different places. A last thing to note about key sentences is that academic 
readers expect them to be at the beginning of the paragraph. (The first sentence this paragraph is a good example of this 
in action!) This placement helps readers comprehend your argument. To see how, try this: find an academic piece (such as a 
textbook or scholarly article) that strikes you as well written and go through part of it reading just the first sentence of 
each paragraph. You should be able to easily follow the sequence of logic. When you’re writing for professors, it is especially 
effective to put your key sentences first because they usually convey your own original thinking. It’s a very good sign when
your paragraphs are typically composed of a telling key sentence followed by evidence and explanation.
Knowing this convention of academic writing can help you both read and write more effectively. When you’re reading a 
complicated academic piece for the first time, you might want to go through reading only the first sentence or two of each 
paragraph to get the overall outline of the argument. Then you can go back and read all of it with a clearer picture of how 
each of the details fit in. And when you’re writing, you may also find it useful to write the first sentence of each paragraph 
(instead of a topic-based outline) to map out a thorough argument before getting immersed in sentence-level wordsmithing."""

In [3]:
def clean_text(text):    
    text = text.lower()
    text = re.sub(r'[\?;,:*)(“”]*', '', text) # replacement of what in the square bracket
    text = re.sub('\w*\d\w*', '', text)# remove digits
    return text

In [5]:
text = clean_text(text)
# text # już trochę obczyszczony

#### Zmień text na listę zdań

In [6]:
list_of_sentences = nltk.tokenize.sent_tokenize(text)
# print(list_of_sentences)
len(list_of_sentences)

16

#### Zmień text na listę wyrazów

In [7]:
# list_of_words = [nltk.word_tokenize(sent) for sent in list_of_sentences] # lista list wyrazów
# print(list_of_words)

#### Funkcja czyszcząca stosowana dla textu

In [7]:
def clean_text(text):    
    text = text.lower()
    text = re.sub(r'[\?,*]*', '', text) # replacement of what in the square bracket
#     text = re.sub('[%s]' % re.escape(string.punctuation), '', text) # remove all punctuation
    text = re.sub('\w*\d\w*', '', text)# remove digits
    text = re.sub('[‘’“”…]', '', text)
#     text = re.sub('\n', '', text)
#     text = re.sub(re.compile(r'\W*\b\w{1,3}\b'), "", text) #remove short words
    text = text.split()
    text = [word for word in text if not word in stopwords.words('english')]
    text = ' '.join(text)
    return text

In [11]:
text_clean = clean_text(text)
# text_clean

In [51]:
clean_sentences = nltk.tokenize.sent_tokenize(text_clean)
len(clean_sentences)
clean_sentences

['versions convey topic pretty easy predict paragraph epidemiological evidence second version establishes argumentative point puts context.',
 'paragraph doesnt describe epidemiological evidence shows epidemiology telling story etiology.',
 'similarly version doesnt relate anything particular version b immediately suggests prior paragraph addresses biological pathway i.e.',
 'etiology disease new paragraph bolster emerging hypothesis different kind evidence.',
 'reader easy keep track paragraph cells chemicals relates paragraph populations different places.',
 'last thing note key sentences academic readers expect beginning paragraph.',
 'first sentence paragraph good example action!',
 'placement helps readers comprehend argument.',
 'see try find academic piece textbook scholarly article strikes well written go part reading first sentence paragraph.',
 'able easily follow sequence logic.',
 'youre writing professors especially effective put key sentences first usually convey original

In [52]:
list_of_numbers = ["one", "two", "three", "foru", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"]

In [63]:
zipped_list = list(zip(list_of_numbers, clean_sentences))
dict_zipped = dict(zipped_list)
dict_zipped

{'one': 'versions convey topic pretty easy predict paragraph epidemiological evidence second version establishes argumentative point puts context.',
 'two': 'paragraph doesnt describe epidemiological evidence shows epidemiology telling story etiology.',
 'three': 'similarly version doesnt relate anything particular version b immediately suggests prior paragraph addresses biological pathway i.e.',
 'foru': 'etiology disease new paragraph bolster emerging hypothesis different kind evidence.',
 'five': 'reader easy keep track paragraph cells chemicals relates paragraph populations different places.',
 'six': 'last thing note key sentences academic readers expect beginning paragraph.',
 'seven': 'first sentence paragraph good example action!',
 'eight': 'placement helps readers comprehend argument.',
 'nine': 'see try find academic piece textbook scholarly article strikes well written go part reading first sentence paragraph.',
 'ten': 'able easily follow sequence logic.',
 'eleven': 'your

In [65]:
dict_zipped['seven']

'first sentence paragraph good example action!'

In [67]:
data_df = pd.DataFrame.from_dict(dict_zipped, orient='index', columns = ['text']) # to to samo co '.transpose'
data_df

text
one     versions convey topic pretty easy predict para...
two     paragraph doesnt describe epidemiological evid...
three   similarly version doesnt relate anything parti...
foru    etiology disease new paragraph bolster emergin...
five    reader easy keep track paragraph cells chemica...
six     last thing note key sentences academic readers...
seven       first sentence paragraph good example action!
eight        placement helps readers comprehend argument.
nine    see try find academic piece textbook scholarly...
ten                    able easily follow sequence logic.
eleven  youre writing professors especially effective ...
twelve  good sign paragraphs typically composed tellin...

In [68]:
full_names = ['Ali Wong', 'Anthony Jeselnik', 'Bill Burr', 'Bo Burnham', 'Dave Chappelle', 'Hasan Minhaj',
              'Jim Jefferies', 'Joe Rogan', 'John Mulaney', 'Louis C.K.', 'Mike Birbiglia', 'Ricky Gervais']

data_df['full_name'] = full_names
data_df

text         full_name
one     versions convey topic pretty easy predict para...          Ali Wong
two     paragraph doesnt describe epidemiological evid...  Anthony Jeselnik
three   similarly version doesnt relate anything parti...         Bill Burr
foru    etiology disease new paragraph bolster emergin...        Bo Burnham
five    reader easy keep track paragraph cells chemica...    Dave Chappelle
six     last thing note key sentences academic readers...      Hasan Minhaj
seven       first sentence paragraph good example action!     Jim Jefferies
eight        placement helps readers comprehend argument.         Joe Rogan
nine    see try find academic piece textbook scholarly...      John Mulaney
ten                    able easily follow sequence logic.        Louis C.K.
eleven  youre writing professors especially effective ...    Mike Birbiglia
twelve  good sign paragraphs typically composed tellin...     Ricky Gervais

#### Lematyzacja

In [14]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [49]:
lemmatizer = WordNetLemmatizer()

In [50]:
for sent in range(len(list_of_sentences)):
    words = nltk.tokenize.word_tokenize(list_of_sentences[sent])
    words = [lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
    list_of_sentences[sent] = ' '.join(words)
    

# print(list_of_sentences[:5])

#### Stemming

In [22]:
from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
stemmed = [porter.stem(word) for word in nltk.tokenize.word_tokenize(text) if word not in stopwords.words('english')] # lista stemowanych słów
# print(stemmed)

In [23]:
stemmed_text = ' '.join(stemmed)
stemmed_text

'version convey topic ’ pretti easi predict paragraph epidemiolog evid second version establish argument point put context . paragraph ’ describ epidemiolog evid show epidemiolog tell stori etiolog . similarli version ’ relat anyth particular version b immedi suggest prior paragraph address biolog pathway i.e . etiolog diseas new paragraph bolster emerg hypothesi differ kind evid . reader ’ easi keep track paragraph cell chemic relat paragraph popul differ place . last thing note key sentenc academ reader expect begin paragraph . first sentenc paragraph good exampl action ! placement help reader comprehend argument . see tri find academ piec textbook scholarli articl strike well written go part read first sentenc paragraph . abl easili follow sequenc logic . ’ write professor especi effect put key sentenc first usual convey origin think . ’ good sign paragraph typic compos tell key sentenc follow evid explan . know convent academ write help read write effect . ’ read complic academ pie

#### Bag of words

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [28]:
cv = CountVectorizer()
x = cv.fit_transform(list_lematized).toarray()
# print(cv.get_feature_names())  # all unique words
print(x.shape)
print(x)

123
(16, 123)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]


In [31]:
cv2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
x2 = cv2.fit_transform(list_lematized).toarray()
# print(cv2.get_feature_names())
print(x2.shape)

(16, 158)


### TF-IDF

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(list_lematized).toarray()
print(x)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.17671311 0.         ... 0.         0.         0.1944453 ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.1851693  0.         0.1851693 ]]


#### Word2Vec

In [43]:
from gensim.models import Word2Vec

In [40]:
clean_sentences = [nltk.tokenize.word_tokenize(sent) for sent in list_lematized]
clean_sentences[:1]

[['version',
  'convey',
  'topic',
  'pretty',
  'easy',
  'predict',
  'paragraph',
  'epidemiological',
  'evidence',
  'second',
  'version',
  'establishes',
  'argumentative',
  'point',
  'put',
  'context',
  '.']]

In [41]:
# for i in range(len(clean_sentences)):
#     clean_sentences[i] = [word for word in clean_sentences[i]]
    
# clean_sentences[:2]

In [44]:
model = Word2Vec(clean_sentences, min_count = 1)

In [48]:
words = model.wv.vocab
words.keys()

dict_keys(['version', 'convey', 'topic', 'pretty', 'easy', 'predict', 'paragraph', 'epidemiological', 'evidence', 'second', 'establishes', 'argumentative', 'point', 'put', 'context', '.', 'doesnt', 'describe', 'show', 'epidemiology', 'telling', 'story', 'etiology', 'similarly', 'relate', 'anything', 'particular', 'b', 'immediately', 'suggests', 'prior', 'address', 'biological', 'pathway', 'i.e', 'disease', 'new', 'bolster', 'emerging', 'hypothesis', 'different', 'kind', 'reader', 'keep', 'track', 'cell', 'chemical', 'relates', 'population', 'place', 'last', 'thing', 'note', 'key', 'sentence', 'academic', 'expect', 'beginning', 'first', 'good', 'example', 'action', '!', 'placement', 'help', 'comprehend', 'argument', 'see', 'try', 'find', 'piece', 'textbook', 'scholarly', 'article', 'strike', 'well', 'written', 'go', 'part', 'reading', 'able', 'easily', 'follow', 'sequence', 'logic', 'youre', 'writing', 'professor', 'especially', 'effective', 'usually', 'original', 'thinking', 'sign', 't

In [46]:
vector = model.wv['typically']
print(vector)

[ 2.7987841e-03 -1.0198011e-03  2.9126145e-03 -8.0333045e-04
  4.2496431e-03  2.4189088e-03  1.0316747e-03  1.1858747e-03
  3.5022229e-03 -2.9382580e-03 -3.9193439e-03  4.6822913e-03
  2.1162038e-03 -3.7339835e-03  2.9501864e-03 -4.9426882e-03
  3.7821936e-03 -4.2679450e-03 -1.2261658e-04 -1.2383031e-03
 -7.3646056e-04 -1.7928991e-03 -4.2361333e-03 -3.5260054e-03
 -2.4465594e-04  1.4505552e-03  4.3029920e-03 -4.0560290e-03
  2.1074633e-03  3.6228399e-03 -7.1388225e-05 -3.4548414e-03
  9.6630334e-04  3.3961469e-03 -2.9625506e-03  2.2700140e-03
  2.2595741e-03  2.3310846e-03 -1.6112643e-03  3.6161682e-03
  4.8443591e-03  1.2364815e-03  6.3326227e-04 -3.5186277e-03
 -4.2175790e-03 -4.4705388e-03  1.4333534e-03  4.4331816e-03
 -2.2545741e-03 -3.6888701e-04  1.4920277e-03  3.8206731e-03
 -1.4024008e-03 -2.7108765e-03  3.3417954e-03  3.4202735e-03
  1.3917643e-03  1.0163561e-03 -1.6529725e-03 -1.6993040e-03
 -2.8067643e-03  2.5792271e-04 -7.5823482e-04  4.4516688e-03
  3.3402902e-03 -6.75383

In [47]:
similar = model.wv.most_similar('typically')
print(similar)

[('topic', 0.24371841549873352), ('knowing', 0.22297829389572144), ('pathway', 0.20408786833286285), ('find', 0.20005543529987335), ('!', 0.185384601354599), ('strike', 0.17985384166240692), ('predict', 0.1773684322834015), ('easily', 0.16775143146514893), ('placement', 0.16273823380470276), ('describe', 0.14144910871982574)]
